package seed

import (
	"strings"

	"github.com/ix-pay/ixpay-pro/internal/domain/base/entity"
	"github.com/ix-pay/ixpay-pro/internal/domain/base/repo"
	"github.com/ix-pay/ixpay-pro/internal/infrastructure/observability/logger"
	"github.com/ix-pay/ixpay-pro/internal/infrastructure/persistence/database"
)

// APISeed API 路由种子数据
type APISeed struct {
	apiRepo repo.APIRepository
}

// NewAPISeed 创建 API 路由种子数据实例
func NewAPISeed(apiRepo repo.APIRepository) Seed {
	return &APISeed{
		apiRepo: apiRepo,
	}
}

// Version 返回种子数据版本
func (as *APISeed) Version() string {
	return "v1.0.0"
}

// Name 返回种子数据名称
func (as *APISeed) Name() string {
	return "api_seed"
}

// Order 返回初始化顺序（第四个执行）
func (as *APISeed) Order() int {
	return 4
}

// Init 初始化 API 路由种子数据
func (as *APISeed) Init(db *database.PostgresDB, logger logger.Logger) error {
	logger.Info("开始初始化 API 路由种子数据")

	// 定义 API 路由种子数据
	apiRoutes := as.getAPIRoutes()

	// 批量插入或更新 API 路由（增量写入）
	for _, apiRoute := range apiRoutes {
		// 检查是否已存在
		existing, err := as.apiRepo.GetByPathAndMethod(apiRoute.Path, apiRoute.Method)
		if err != nil {
			// 不存在则创建
			if err := as.apiRepo.Create(apiRoute); err != nil {
				logger.Error("创建 API 路由失败", "path", apiRoute.Path, "method", apiRoute.Method, "group", apiRoute.Group, "error", err)
				return err
			}
			logger.Info("创建 API 路由成功", "path", apiRoute.Path, "method", apiRoute.Method, "group", apiRoute.Group)
		} else {
			// 存在则更新
			existing.Group = apiRoute.Group
			existing.AuthRequired = apiRoute.AuthRequired
			existing.AuthType = apiRoute.AuthType
			existing.Description = apiRoute.Description
			existing.Status = apiRoute.Status
			if err := as.apiRepo.Update(existing); err != nil {
				logger.Error("更新 API 路由失败", "path", apiRoute.Path, "method", apiRoute.Method, "error", err)
				return err
			}
			logger.Info("更新 API 路由成功", "id", existing.ID, "path", apiRoute.Path, "method", apiRoute.Method, "group", apiRoute.Group)
		}
	}

	logger.Info("API 路由种子数据初始化完成", "total", len(apiRoutes))
	return nil
}

// getAPIRoutes 获取所有 API 路由定义
func (as *APISeed) getAPIRoutes() []*entity.API {
	apis := []*entity.API{
		// ==================== 认证管理 ====================
		{
			Path:         "/api/admin/auth/register",
			Method:       "POST",
			Group:        "认证管理",
			AuthRequired: false,
			AuthType:     1,
			Description:  "用户注册",
			Status:       1,
		},
		{
			Path:         "/api/admin/auth/login",
			Method:       "POST",
			Group:        "认证管理",
			AuthRequired: false,
			AuthType:     1,
			Description:  "用户登录",
			Status:       1,
		},
		{
			Path:         "/api/admin/auth/captcha",
			Method:       "POST",
			Group:        "认证管理",
			AuthRequired: false,
			AuthType:     1,
			Description:  "获取验证码",
			Status:       1,
		},
		{
			Path:         "/api/admin/auth/refresh-token",
			Method:       "POST",
			Group:        "认证管理",
			AuthRequired: true,
			AuthType:     0,
			Description:  "刷新令牌",
			Status:       1,
		},
		{
			Path:         "/api/admin/auth/logout",
			Method:       "POST",
			Group:        "认证管理",
			AuthRequired: true,
			AuthType:     0,
			Description:  "用户登出",
			Status:       1,
		},

		// ==================== 用户管理 ====================
		{
			Path:         "/api/admin/user/info",
			Method:       "GET",
			Group:        "用户管理",
			AuthRequired: true,
			AuthType:     0,
			Description:  "获取当前用户信息",
			Status:       1,
		},
		{
			Path:         "/api/admin/user/info",
			Method:       "PUT",
			Group:        "用户管理",
			AuthRequired: true,
			AuthType:     0,
			Description:  "更新当前用户信息",
			Status:       1,
		},
		{
			Path:         "/api/admin/user/info/password",
			Method:       "PUT",
			Group:        "用户管理",
			AuthRequired: true,
			AuthType:     0,
			Description:  "修改当前用户密码",
			Status:       1,
		},
		{
			Path:         "/api/admin/user",
			Method:       "GET",
			Group:        "用户管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取用户列表",
			Status:       1,
		},
		{
			Path:         "/api/admin/user",
			Method:       "POST",
			Group:        "用户管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "创建用户",
			Status:       1,
		},
		{
			Path:         "/api/admin/user/:id",
			Method:       "GET",
			Group:        "用户管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取用户详情",
			Status:       1,
		},
		{
			Path:         "/api/admin/user/:id",
			Method:       "PUT",
			Group:        "用户管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "更新用户",
			Status:       1,
		},
		{
			Path:         "/api/admin/user/:id",
			Method:       "DELETE",
			Group:        "用户管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "删除用户",
			Status:       1,
		},
		{
			Path:         "/api/admin/user/password/reset",
			Method:       "PUT",
			Group:        "用户管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "重置用户密码",
			Status:       1,
		},
		{
			Path:         "/api/admin/user/switch-role",
			Method:       "POST",
			Group:        "用户管理",
			AuthRequired: true,
			AuthType:     0,
			Description:  "切换用户角色",
			Status:       1,
		},
		{
			Path:         "/api/admin/user/get-user-settings",
			Method:       "GET",
			Group:        "用户管理",
			AuthRequired: true,
			AuthType:     0,
			Description:  "获取用户个人设置",
			Status:       1,
		},
		{
			Path:         "/api/admin/user/update-user-settings",
			Method:       "PUT",
			Group:        "用户管理",
			AuthRequired: true,
			AuthType:     0,
			Description:  "更新用户个人设置",
			Status:       1,
		},

		// ==================== 角色管理 ====================
		{
			Path:         "/api/admin/roles",
			Method:       "GET",
			Group:        "角色管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取角色列表",
			Status:       1,
		},
		{
			Path:         "/api/admin/roles",
			Method:       "POST",
			Group:        "角色管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "创建角色",
			Status:       1,
		},
		{
			Path:         "/api/admin/roles/:id",
			Method:       "GET",
			Group:        "角色管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取角色详情",
			Status:       1,
		},
		{
			Path:         "/api/admin/roles/:id",
			Method:       "PUT",
			Group:        "角色管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "更新角色",
			Status:       1,
		},
		{
			Path:         "/api/admin/roles/:id",
			Method:       "DELETE",
			Group:        "角色管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "删除角色",
			Status:       1,
		},
		{
			Path:         "/api/admin/roles/:id/apis",
			Method:       "GET",
			Group:        "角色管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取角色已授权 API 列表",
			Status:       1,
		},
		{
			Path:         "/api/admin/roles/:id/apis/available",
			Method:       "GET",
			Group:        "角色管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取角色可授权的 API 列表",
			Status:       1,
		},
		{
			Path:         "/api/admin/roles/:id/apis",
			Method:       "PUT",
			Group:        "角色管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "分配角色 API 权限",
			Status:       1,
		},
		{
			Path:         "/api/admin/roles/:id",
			Method:       "GET",
			Group:        "角色管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取角色详情",
			Status:       1,
		},
		{
			Path:         "/api/admin/roles/:id/detail",
			Method:       "GET",
			Group:        "角色管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取角色详情（路径参数）",
			Status:       1,
		},
		{
			Path:         "/api/admin/roles/:id/available-apis",
			Method:       "GET",
			Group:        "角色管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取角色可授权的 API 列表",
			Status:       1,
		},
		{
			Path:         "/api/admin/roles/assign-users",
			Method:       "POST",
			Group:        "角色管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "分配用户到角色",
			Status:       1,
		},
		{
			Path:         "/api/admin/roles/assign-menus",
			Method:       "POST",
			Group:        "角色管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "分配菜单到角色",
			Status:       1,
		},
		{
			Path:         "/api/admin/roles/assign-api-routes",
			Method:       "POST",
			Group:        "角色管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "分配 API 路由到角色",
			Status:       1,
		},
		{
			Path:         "/api/admin/roles/all",
			Method:       "GET",
			Group:        "角色管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取所有角色",
			Status:       1,
		},

		// ==================== 菜单管理 ====================
		{
			Path:         "/api/admin/menu",
			Method:       "GET",
			Group:        "菜单管理",
			AuthRequired: true,
			AuthType:     0,
			Description:  "获取用户菜单树",
			Status:       1,
		},
		{
			Path:         "/api/admin/menu",
			Method:       "POST",
			Group:        "菜单管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "创建菜单",
			Status:       1,
		},
		{
			Path:         "/api/admin/menu/:id",
			Method:       "GET",
			Group:        "菜单管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取菜单详情",
			Status:       1,
		},
		{
			Path:         "/api/admin/menu/:id",
			Method:       "PUT",
			Group:        "菜单管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "更新菜单",
			Status:       1,
		},
		{
			Path:         "/api/admin/menu/:id",
			Method:       "DELETE",
			Group:        "菜单管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "删除菜单",
			Status:       1,
		},
		{
			Path:         "/api/admin/menu/tree",
			Method:       "GET",
			Group:        "菜单管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取完整菜单树",
			Status:       1,
		},
		{
			Path:         "/api/admin/menu/page",
			Method:       "GET",
			Group:        "菜单管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取菜单分页列表",
			Status:       1,
		},

		// ==================== API 管理 ====================
		{
			Path:         "/api/admin/apis",
			Method:       "GET",
			Group:        "API 管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取 API 列表",
			Status:       1,
		},
		{
			Path:         "/api/admin/apis/:id",
			Method:       "GET",
			Group:        "API 管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取 API 详情",
			Status:       1,
		},
		{
			Path:         "/api/admin/apis",
			Method:       "POST",
			Group:        "API 管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "创建 API",
			Status:       1,
		},
		{
			Path:         "/api/admin/apis/:id",
			Method:       "PUT",
			Group:        "API 管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "更新 API",
			Status:       1,
		},
		{
			Path:         "/api/admin/apis/:id",
			Method:       "DELETE",
			Group:        "API 管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "删除 API",
			Status:       1,
		},

		// ==================== 字典管理 ====================
		{
			Path:         "/api/admin/dict",
			Method:       "GET",
			Group:        "字典管理",
			AuthRequired: true,
			AuthType:     0,
			Description:  "获取字典列表",
			Status:       1,
		},
		{
			Path:         "/api/admin/dict",
			Method:       "POST",
			Group:        "字典管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "创建字典",
			Status:       1,
		},
		{
			Path:         "/api/admin/dict/:id",
			Method:       "GET",
			Group:        "字典管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取字典详情",
			Status:       1,
		},
		{
			Path:         "/api/admin/dict/:id",
			Method:       "PUT",
			Group:        "字典管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "更新字典",
			Status:       1,
		},
		{
			Path:         "/api/admin/dict/:id",
			Method:       "DELETE",
			Group:        "字典管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "删除字典",
			Status:       1,
		},
		{
			Path:         "/api/admin/dict/code",
			Method:       "GET",
			Group:        "字典管理",
			AuthRequired: true,
			AuthType:     0,
			Description:  "根据 code 获取字典",
			Status:       1,
		},
		{
			Path:         "/api/admin/dict/item",
			Method:       "GET",
			Group:        "字典管理",
			AuthRequired: true,
			AuthType:     0,
			Description:  "获取字典项列表",
			Status:       1,
		},
		{
			Path:         "/api/admin/dict/item",
			Method:       "POST",
			Group:        "字典管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "创建字典项",
			Status:       1,
		},
		{
			Path:         "/api/admin/dict/item/:id",
			Method:       "GET",
			Group:        "字典管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取字典项详情",
			Status:       1,
		},
		{
			Path:         "/api/admin/dict/item/:id",
			Method:       "PUT",
			Group:        "字典管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "更新字典项",
			Status:       1,
		},
		{
			Path:         "/api/admin/dict/item/:id",
			Method:       "DELETE",
			Group:        "字典管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "删除字典项",
			Status:       1,
		},
		{
			Path:         "/api/admin/dict/items",
			Method:       "GET",
			Group:        "字典管理",
			AuthRequired: true,
			AuthType:     0,
			Description:  "根据字典 ID 获取字典项列表",
			Status:       1,
		},

		// ==================== 部门管理 ====================
		{
			Path:         "/api/admin/department",
			Method:       "GET",
			Group:        "部门管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取部门列表",
			Status:       1,
		},
		{
			Path:         "/api/admin/department",
			Method:       "POST",
			Group:        "部门管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "创建部门",
			Status:       1,
		},
		{
			Path:         "/api/admin/department/:id",
			Method:       "GET",
			Group:        "部门管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取部门详情",
			Status:       1,
		},
		{
			Path:         "/api/admin/department/:id",
			Method:       "PUT",
			Group:        "部门管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "更新部门",
			Status:       1,
		},
		{
			Path:         "/api/admin/department/:id",
			Method:       "DELETE",
			Group:        "部门管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "删除部门",
			Status:       1,
		},
		{
			Path:         "/api/admin/department/tree",
			Method:       "GET",
			Group:        "部门管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取部门树",
			Status:       1,
		},
		{
			Path:         "/api/admin/department/:id/leader",
			Method:       "PUT",
			Group:        "部门管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "更新部门负责人",
			Status:       1,
		},

		// ==================== 岗位管理 ====================
		{
			Path:         "/api/admin/position",
			Method:       "GET",
			Group:        "岗位管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取岗位列表",
			Status:       1,
		},
		{
			Path:         "/api/admin/position",
			Method:       "POST",
			Group:        "岗位管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "创建岗位",
			Status:       1,
		},
		{
			Path:         "/api/admin/position/:id",
			Method:       "GET",
			Group:        "岗位管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取岗位详情",
			Status:       1,
		},
		{
			Path:         "/api/admin/position/:id",
			Method:       "PUT",
			Group:        "岗位管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "更新岗位",
			Status:       1,
		},
		{
			Path:         "/api/admin/position/:id",
			Method:       "DELETE",
			Group:        "岗位管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "删除岗位",
			Status:       1,
		},
		{
			Path:         "/api/admin/position/all",
			Method:       "GET",
			Group:        "岗位管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取所有岗位",
			Status:       1,
		},

		// ==================== 按钮权限管理 ====================
		{
			Path:         "/api/admin/btn-perms",
			Method:       "GET",
			Group:        "按钮权限管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取按钮权限列表",
			Status:       1,
		},
		{
			Path:         "/api/admin/btn-perms",
			Method:       "POST",
			Group:        "按钮权限管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "创建按钮权限",
			Status:       1,
		},
		{
			Path:         "/api/admin/btn-perms/:id",
			Method:       "GET",
			Group:        "按钮权限管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取按钮权限详情",
			Status:       1,
		},
		{
			Path:         "/api/admin/btn-perms/:id",
			Method:       "PUT",
			Group:        "按钮权限管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "更新按钮权限",
			Status:       1,
		},
		{
			Path:         "/api/admin/btn-perms/:id",
			Method:       "DELETE",
			Group:        "按钮权限管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "删除按钮权限",
			Status:       1,
		},
		{
			Path:         "/api/admin/btn-perms/:id",
			Method:       "GET",
			Group:        "按钮权限管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取按钮权限详情",
			Status:       1,
		},
		{
			Path:         "/api/admin/btn-perms/assign-api-routes",
			Method:       "POST",
			Group:        "按钮权限管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "分配 API 路由到按钮权限",
			Status:       1,
		},
		{
			Path:         "/api/admin/btn-perms/revoke-api-route",
			Method:       "POST",
			Group:        "按钮权限管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "从按钮权限撤销 API 路由",
			Status:       1,
		},
		{
			Path:         "/api/admin/btn-perms/assign-to-role",
			Method:       "POST",
			Group:        "按钮权限管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "分配按钮权限到角色",
			Status:       1,
		},
		{
			Path:         "/api/admin/btn-perms/revoke-from-role",
			Method:       "POST",
			Group:        "按钮权限管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "从角色撤销按钮权限",
			Status:       1,
		},
		{
			Path:         "/api/admin/btn-perms/api-routes",
			Method:       "GET",
			Group:        "按钮权限管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取按钮权限关联的 API 路由",
			Status:       1,
		},
		{
			Path:         "/api/admin/btn-perms/for-route",
			Method:       "GET",
			Group:        "按钮权限管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "根据 API 路由获取按钮权限",
			Status:       1,
		},
		{
			Path:         "/api/admin/btn-perms/by-role",
			Method:       "GET",
			Group:        "按钮权限管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "根据角色获取按钮权限",
			Status:       1,
		},
		{
			Path:         "/api/admin/btn-perms/by-menu",
			Method:       "GET",
			Group:        "按钮权限管理",
			AuthRequired: true,
			AuthType:     1,
			Description:  "根据菜单获取按钮权限",
			Status:       1,
		},

		// ==================== 系统配置 ====================
		{
			Path:         "/api/admin/config",
			Method:       "GET",
			Group:        "系统配置",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取系统配置列表",
			Status:       1,
		},
		{
			Path:         "/api/admin/config",
			Method:       "POST",
			Group:        "系统配置",
			AuthRequired: true,
			AuthType:     1,
			Description:  "创建系统配置",
			Status:       1,
		},
		{
			Path:         "/api/admin/config/:key",
			Method:       "GET",
			Group:        "系统配置",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取系统配置详情",
			Status:       1,
		},
		{
			Path:         "/api/admin/config/:key",
			Method:       "PUT",
			Group:        "系统配置",
			AuthRequired: true,
			AuthType:     1,
			Description:  "更新系统配置",
			Status:       1,
		},
		{
			Path:         "/api/admin/config/:key",
			Method:       "DELETE",
			Group:        "系统配置",
			AuthRequired: true,
			AuthType:     1,
			Description:  "删除系统配置",
			Status:       1,
		},
		{
			Path:         "/api/admin/config/key",
			Method:       "GET",
			Group:        "系统配置",
			AuthRequired: true,
			AuthType:     1,
			Description:  "根据键获取系统配置",
			Status:       1,
		},
		{
			Path:         "/api/admin/config/active",
			Method:       "GET",
			Group:        "系统配置",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取所有启用的配置",
			Status:       1,
		},

		// ==================== 通知公告 ====================
		{
			Path:         "/api/admin/notice",
			Method:       "GET",
			Group:        "通知公告",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取公告列表",
			Status:       1,
		},
		{
			Path:         "/api/admin/notice",
			Method:       "POST",
			Group:        "通知公告",
			AuthRequired: true,
			AuthType:     1,
			Description:  "创建公告",
			Status:       1,
		},
		{
			Path:         "/api/admin/notice/:id",
			Method:       "GET",
			Group:        "通知公告",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取公告详情",
			Status:       1,
		},
		{
			Path:         "/api/admin/notice/:id",
			Method:       "PUT",
			Group:        "通知公告",
			AuthRequired: true,
			AuthType:     1,
			Description:  "更新公告",
			Status:       1,
		},
		{
			Path:         "/api/admin/notice/:id",
			Method:       "DELETE",
			Group:        "通知公告",
			AuthRequired: true,
			AuthType:     1,
			Description:  "删除公告",
			Status:       1,
		},
		{
			Path:         "/api/admin/notice/:id/publish",
			Method:       "POST",
			Group:        "通知公告",
			AuthRequired: true,
			AuthType:     1,
			Description:  "发布公告",
			Status:       1,
		},
		{
			Path:         "/api/admin/notice/:id/read",
			Method:       "POST",
			Group:        "通知公告",
			AuthRequired: true,
			AuthType:     1,
			Description:  "标记公告已读",
			Status:       1,
		},
		{
			Path:         "/api/admin/notice/:id/is-read",
			Method:       "GET",
			Group:        "通知公告",
			AuthRequired: true,
			AuthType:     1,
			Description:  "检查公告是否已读",
			Status:       1,
		},
		{
			Path:         "/api/admin/notice/statistics",
			Method:       "GET",
			Group:        "通知公告",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取公告统计",
			Status:       1,
		},

		// ==================== 操作日志 ====================
		{
			Path:         "/api/admin/logs",
			Method:       "GET",
			Group:        "操作日志",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取操作日志列表",
			Status:       1,
		},
		{
			Path:         "/api/admin/logs/:id",
			Method:       "GET",
			Group:        "操作日志",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取操作日志详情",
			Status:       1,
		},
		{
			Path:         "/api/admin/logs/:id",
			Method:       "DELETE",
			Group:        "操作日志",
			AuthRequired: true,
			AuthType:     1,
			Description:  "删除操作日志",
			Status:       1,
		},
		{
			Path:         "/api/admin/logs/batch-delete",
			Method:       "POST",
			Group:        "操作日志",
			AuthRequired: true,
			AuthType:     1,
			Description:  "批量删除操作日志",
			Status:       1,
		},
		{
			Path:         "/api/admin/logs/statistics",
			Method:       "GET",
			Group:        "操作日志",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取操作日志统计",
			Status:       1,
		},
		{
			Path:         "/api/admin/logs/clear",
			Method:       "POST",
			Group:        "操作日志",
			AuthRequired: true,
			AuthType:     1,
			Description:  "清空操作日志",
			Status:       1,
		},

		// ==================== 登录日志 ====================
		{
			Path:         "/api/admin/login-log",
			Method:       "GET",
			Group:        "登录日志",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取登录日志列表",
			Status:       1,
		},
		{
			Path:         "/api/admin/login-log/:id",
			Method:       "GET",
			Group:        "登录日志",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取登录日志详情",
			Status:       1,
		},
		{
			Path:         "/api/admin/login-log/statistics",
			Method:       "GET",
			Group:        "登录日志",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取登录日志统计",
			Status:       1,
		},
		{
			Path:         "/api/admin/login-log/abnormal",
			Method:       "GET",
			Group:        "登录日志",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取异常登录查询",
			Status:       1,
		},
		{
			Path:         "/api/admin/login-log",
			Method:       "POST",
			Group:        "登录日志",
			AuthRequired: true,
			AuthType:     1,
			Description:  "记录登录日志",
			Status:       1,
		},

		// ==================== 在线用户 ====================
		{
			Path:         "/api/admin/online-user",
			Method:       "GET",
			Group:        "在线用户",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取在线用户列表",
			Status:       1,
		},
		{
			Path:         "/api/admin/online-user/:user_id",
			Method:       "GET",
			Group:        "在线用户",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取在线用户详情",
			Status:       1,
		},
		{
			Path:         "/api/admin/online-user/:user_id",
			Method:       "DELETE",
			Group:        "在线用户",
			AuthRequired: true,
			AuthType:     1,
			Description:  "强制用户下线",
			Status:       1,
		},
		{
			Path:         "/api/admin/online-user/count",
			Method:       "GET",
			Group:        "在线用户",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取在线用户数量",
			Status:       1,
		},
		{
			Path:         "/api/admin/online-user/online",
			Method:       "GET",
			Group:        "在线用户",
			AuthRequired: true,
			AuthType:     1,
			Description:  "检查用户是否在线",
			Status:       1,
		},
		{
			Path:         "/api/admin/online-user/batch",
			Method:       "POST",
			Group:        "在线用户",
			AuthRequired: true,
			AuthType:     1,
			Description:  "批量强制用户下线",
			Status:       1,
		},

		// ==================== 系统监控 ====================
		{
			Path:         "/api/admin/monitor/system",
			Method:       "GET",
			Group:        "系统监控",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取系统监控信息",
			Status:       1,
		},
		{
			Path:         "/api/admin/monitor/cache",
			Method:       "GET",
			Group:        "系统监控",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取缓存监控信息",
			Status:       1,
		},
		{
			Path:         "/api/admin/monitor/database",
			Method:       "GET",
			Group:        "系统监控",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取数据库监控信息",
			Status:       1,
		},
		{
			Path:         "/api/admin/monitor/redis-keys",
			Method:       "GET",
			Group:        "系统监控",
			AuthRequired: true,
			AuthType:     1,
			Description:  "查询 Redis 键",
			Status:       1,
		},
		{
			Path:         "/api/admin/monitor/slow-queries",
			Method:       "GET",
			Group:        "系统监控",
			AuthRequired: true,
			AuthType:     1,
			Description:  "查询慢查询日志",
			Status:       1,
		},

		// ==================== 定时任务 ====================
		{
			Path:         "/api/admin/task",
			Method:       "GET",
			Group:        "定时任务",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取定时任务列表",
			Status:       1,
		},
		{
			Path:         "/api/admin/task",
			Method:       "POST",
			Group:        "定时任务",
			AuthRequired: true,
			AuthType:     1,
			Description:  "创建定时任务",
			Status:       1,
		},
		{
			Path:         "/api/admin/task/:id",
			Method:       "GET",
			Group:        "定时任务",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取定时任务详情",
			Status:       1,
		},
		{
			Path:         "/api/admin/task/:id",
			Method:       "DELETE",
			Group:        "定时任务",
			AuthRequired: true,
			AuthType:     1,
			Description:  "删除定时任务",
			Status:       1,
		},
		{
			Path:         "/api/admin/task/:id/start",
			Method:       "POST",
			Group:        "定时任务",
			AuthRequired: true,
			AuthType:     1,
			Description:  "启动定时任务",
			Status:       1,
		},
		{
			Path:         "/api/admin/task/:id/stop",
			Method:       "POST",
			Group:        "定时任务",
			AuthRequired: true,
			AuthType:     1,
			Description:  "停止定时任务",
			Status:       1,
		},
		{
			Path:         "/api/admin/task/:id/retry",
			Method:       "POST",
			Group:        "定时任务",
			AuthRequired: true,
			AuthType:     1,
			Description:  "重试定时任务",
			Status:       1,
		},
		{
			Path:         "/api/admin/task/:id/execution-logs",
			Method:       "GET",
			Group:        "定时任务",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取任务执行日志",
			Status:       1,
		},
		{
			Path:         "/api/admin/task/statistics",
			Method:       "GET",
			Group:        "定时任务",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取任务统计",
			Status:       1,
		},
		{
			Path:         "/api/admin/task/:id/group",
			Method:       "POST",
			Group:        "定时任务",
			AuthRequired: true,
			AuthType:     1,
			Description:  "设置任务分组",
			Status:       1,
		},

		// ==================== 权限审计日志 ====================
		{
			Path:         "/api/admin/permission-logs",
			Method:       "GET",
			Group:        "权限审计日志",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取权限日志列表",
			Status:       1,
		},
		{
			Path:         "/api/admin/permission-logs/roles/:id/permission-logs",
			Method:       "GET",
			Group:        "权限审计日志",
			AuthRequired: true,
			AuthType:     1,
			Description:  "获取角色权限日志",
			Status:       1,
		},
	}

	// 批量替换所有双斜杠为单斜杠
	for _, api := range apis {
		api.Path = strings.ReplaceAll(api.Path, "//", "/")
	}

	return apis
}
