version: '3.8'

services:
  ixpay-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ixpay-server
    ports:
      - "8586:8586"
    volumes:
      - ./configs/config.yaml:/app/configs/config.yaml:ro
      - ./logs:/app/logs
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_USER=magic
      - DB_PASSWORD=magic@520
      - DB_NAME=ixpay-pro
      - REDIS_HOST=app-redis-1
      - REDIS_PORT=6379
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ixpay-network
    restart: unless-stopped

networks:
  ixpay-network:
    driver: bridge
