// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/google/wire"
	"github.com/ix-pay/ixpay-pro/internal/app/base"
	"github.com/ix-pay/ixpay-pro/internal/app/base/api"
	"github.com/ix-pay/ixpay-pro/internal/app/wx"
	"github.com/ix-pay/ixpay-pro/internal/app/wx/api"
	"github.com/ix-pay/ixpay-pro/internal/config"
	"github.com/ix-pay/ixpay-pro/internal/domain/base/service"
	service2 "github.com/ix-pay/ixpay-pro/internal/domain/wx/service"
	"github.com/ix-pay/ixpay-pro/internal/infrastructure/observability/logger"
	"github.com/ix-pay/ixpay-pro/internal/infrastructure/observability/monitor"
	"github.com/ix-pay/ixpay-pro/internal/infrastructure/persistence/cache"
	"github.com/ix-pay/ixpay-pro/internal/infrastructure/persistence/database"
	"github.com/ix-pay/ixpay-pro/internal/infrastructure/persistence/redis"
	"github.com/ix-pay/ixpay-pro/internal/infrastructure/security/auth"
	"github.com/ix-pay/ixpay-pro/internal/infrastructure/security/captcha"
	"github.com/ix-pay/ixpay-pro/internal/infrastructure/support/snowflake"
	"github.com/ix-pay/ixpay-pro/internal/infrastructure/support/task"
	"github.com/ix-pay/ixpay-pro/internal/persistence/base"
	persistence2 "github.com/ix-pay/ixpay-pro/internal/persistence/wx"
	redis2 "github.com/redis/go-redis/v9"
)

import (
	_ "github.com/ix-pay/ixpay-pro/docs"
)

// Injectors from wire.go:

// 初始化完整应用
func InitializeApp() (*Application, error) {
	configConfig, err := config.LoadConfig()
	if err != nil {
		return nil, err
	}
	multiLogger := logger.SetupMultiLogger(configConfig)
	loggerLogger := logger.SetupLogger(configConfig)
	postgresDB, err := database.SetupPostgresDB(configConfig, loggerLogger)
	if err != nil {
		return nil, err
	}
	snowflakeSnowflake, err := snowflake.SetupSnowflake(configConfig)
	if err != nil {
		return nil, err
	}
	jwtAuth, err := auth.SetupJWTAuth(configConfig, loggerLogger)
	if err != nil {
		return nil, err
	}
	redisClient, err := redis.SetupRedisClient(configConfig, loggerLogger)
	if err != nil {
		return nil, err
	}
	cacheCache, err := cache.SetupCache(configConfig, redisClient)
	if err != nil {
		return nil, err
	}
	permissionManager := auth.SetupPermissionManager(cacheCache, loggerLogger)
	userRepository := persistence.NewUserRepository(postgresDB)
	userSettingRepository := persistence.NewUserSettingRepository(postgresDB)
	roleRepository := persistence.NewRoleRepository(postgresDB)
	menuRepository := persistence.NewMenuRepository(postgresDB)
	apiRepository := persistence.NewAPIRepository(postgresDB)
	btnPermRepository := persistence.NewBtnPermRepository(postgresDB)
	permissionGroupRepository := persistence.NewPermissionGroupRepository(postgresDB)
	roleService := service.NewRoleService(roleRepository, userRepository, menuRepository, apiRepository, btnPermRepository, permissionGroupRepository, loggerLogger)
	rolePermissionService := service.NewRolePermissionService(postgresDB, roleRepository, menuRepository, btnPermRepository, apiRepository, cacheCache, loggerLogger)
	captchaCaptcha, err := captcha.SetupCaptcha(configConfig, redisClient)
	if err != nil {
		return nil, err
	}
	loginLogRepository := persistence.NewLoginLogRepository(postgresDB)
	loginLogService := service.NewLoginLogService(loginLogRepository, loggerLogger)
	userService := service.NewUserService(userRepository, userSettingRepository, roleService, rolePermissionService, jwtAuth, configConfig, loggerLogger, cacheCache, captchaCaptcha, loginLogService)
	authController := baseapi.NewAuthController(userService, jwtAuth, loggerLogger)
	userController := baseapi.NewUserController(userService, loggerLogger)
	taskManager := task.SetupTaskManager(loggerLogger)
	taskExecutionLogRepository := persistence.NewTaskExecutionLogRepository(postgresDB)
	taskExecutionLogService := service.NewTaskExecutionLogService(taskExecutionLogRepository, loggerLogger)
	taskController := baseapi.NewTaskController(taskManager, loggerLogger, taskExecutionLogService)
	apiService := service.NewAPIService(apiRepository, loggerLogger)
	apiController := baseapi.NewAPIController(apiService, loggerLogger)
	menuService := service.NewMenuService(menuRepository, btnPermRepository, roleRepository, apiRepository, loggerLogger)
	menuController := baseapi.NewMenuController(menuService, loggerLogger)
	roleController := baseapi.NewRoleController(roleService, rolePermissionService, apiService, loggerLogger)
	btnPermService := service.NewBtnPermService(btnPermRepository, loggerLogger)
	permissionRuleRepository := persistence.NewPermissionRuleRepository(postgresDB)
	permissionService := service.NewPermissionService(roleService, userService, roleRepository, btnPermRepository, apiRepository, permissionRuleRepository, permissionGroupRepository, loggerLogger)
	btnPermController := baseapi.NewBtnPermController(btnPermService, permissionService, roleService, loggerLogger)
	configRepository := persistence.NewConfigRepository(postgresDB)
	configService := service.NewConfigService(configRepository, loggerLogger)
	configController := baseapi.NewConfigController(configService, loggerLogger)
	dictRepository := persistence.NewDictRepository(postgresDB)
	dictService := service.NewDictService(dictRepository, loggerLogger)
	dictItemRepository := persistence.NewDictItemRepository(postgresDB)
	dictItemService := service.NewDictItemService(dictItemRepository, dictRepository, loggerLogger)
	dictController := baseapi.NewDictController(dictService, dictItemService, loggerLogger)
	operationLogRepository := persistence.NewOperationLogRepository(postgresDB)
	operationLogService := service.NewOperationLogService(operationLogRepository, loggerLogger)
	operationLogController := baseapi.NewOperationLogController(operationLogService)
	departmentRepository := persistence.NewDepartmentRepository(postgresDB)
	departmentService := service.NewDepartmentService(departmentRepository, loggerLogger)
	departmentController := baseapi.NewDepartmentController(departmentService, loggerLogger)
	positionRepository := persistence.NewPositionRepository(postgresDB)
	positionService := service.NewPositionService(positionRepository, loggerLogger)
	positionController := baseapi.NewPositionController(positionService, loggerLogger)
	noticeRepository := persistence.NewNoticeRepository(postgresDB)
	noticeReadRecordRepository := persistence.NewNoticeReadRecordRepository(postgresDB)
	noticeService := service.NewNoticeService(noticeRepository, noticeReadRecordRepository, loggerLogger)
	noticeReadRecordService := service.NewNoticeReadRecordService(noticeReadRecordRepository, loggerLogger)
	noticeController := baseapi.NewNoticeController(noticeService, noticeReadRecordService, loggerLogger)
	loginLogController := baseapi.NewLoginLogController(loginLogService, loggerLogger)
	onlineUserRepository := persistence.NewOnlineUserRepository(cacheCache)
	onlineUserService := service.NewOnlineUserService(onlineUserRepository, loggerLogger)
	onlineUserController := baseapi.NewOnlineUserController(onlineUserService, loggerLogger)
	systemMonitor := monitor.SetupSystemMonitor()
	client := ProvideRedisClient(redisClient)
	cacheMonitor := monitor.SetupCacheMonitor(client)
	databaseMonitor := monitor.SetupDatabaseMonitor(postgresDB, configConfig, loggerLogger)
	monitorController := baseapi.NewMonitorController(systemMonitor, cacheMonitor, databaseMonitor)
	appBase, err := base.NewAppBase(loggerLogger, configConfig, postgresDB, jwtAuth, permissionManager, authController, userController, taskController, apiController, menuController, roleController, btnPermController, configController, dictController, operationLogController, departmentController, positionController, noticeController, loginLogController, onlineUserController, monitorController, userRepository, apiRepository, roleRepository, menuRepository, configRepository, dictRepository, operationLogService, onlineUserService, taskExecutionLogRepository, cacheCache)
	if err != nil {
		return nil, err
	}
	wxUserRepository := persistence2.NewWXUserRepository(postgresDB)
	wxAuthSessionRepository := persistence2.NewWXAuthSessionRepository(postgresDB)
	wxAuthService := service2.NewWXAuthService(jwtAuth, loggerLogger, wxUserRepository, wxAuthSessionRepository, configRepository)
	wxapiAuthController := wxapi.NewAuthController(wxAuthService, loggerLogger)
	paymentRepository := persistence2.NewPaymentRepository(postgresDB)
	paymentService := service2.NewPaymentService(paymentRepository, taskManager, configRepository, loggerLogger)
	paymentController := wxapi.NewPaymentController(paymentService, loggerLogger)
	appWX, err := wx.NewAppWX(loggerLogger, postgresDB, jwtAuth, permissionManager, wxapiAuthController, paymentController)
	if err != nil {
		return nil, err
	}
	application, err := SetupApplication(configConfig, multiLogger, loggerLogger, postgresDB, snowflakeSnowflake, jwtAuth, permissionManager, cacheCache, appBase, appWX)
	if err != nil {
		return nil, err
	}
	return application, nil
}

// wire.go:

// 定义全局服务提供者集合
var GlobalServiceSet = wire.NewSet(config.LoadConfig, logger.SetupMultiLogger, logger.SetupLogger, database.SetupPostgresDB, redis.SetupRedisClient, cache.SetupCache, snowflake.SetupSnowflake, captcha.SetupCaptcha, auth.SetupJWTAuth, auth.SetupPermissionManager, task.SetupTaskManager, ProvideRedisClient,

	SetupApplication,
)

// ProvideRedisClient 提供 Redis 客户端
func ProvideRedisClient(redisClient *redis.RedisClient) *redis2.Client {
	return redisClient.Client
}

var ProviderSet = wire.NewSet(base.ProviderSetBaseMonitor, base.ProviderSetBaseRepo, wx.ProviderSetWXRepo, base.ProviderSetBaseService, wx.ProviderSetWXService, base.ProviderSetBaseConverter, base.ProviderSetBaseController, wx.ProviderSetWXController, base.ProviderSetBaseApp, wx.ProviderSetWXApp)
