// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/google/wire"
	"github.com/ix-pay/ixpay-pro/internal/app/base"
	"github.com/ix-pay/ixpay-pro/internal/app/base/api/v1"
	repository2 "github.com/ix-pay/ixpay-pro/internal/app/base/domain/repository"
	service2 "github.com/ix-pay/ixpay-pro/internal/app/base/domain/service"
	"github.com/ix-pay/ixpay-pro/internal/app/wx"
	"github.com/ix-pay/ixpay-pro/internal/app/wx/api/v1"
	"github.com/ix-pay/ixpay-pro/internal/app/wx/domain/repository"
	"github.com/ix-pay/ixpay-pro/internal/app/wx/domain/service"
	"github.com/ix-pay/ixpay-pro/internal/config"
	"github.com/ix-pay/ixpay-pro/internal/infrastructure/auth"
	"github.com/ix-pay/ixpay-pro/internal/infrastructure/database"
	"github.com/ix-pay/ixpay-pro/internal/infrastructure/logger"
	"github.com/ix-pay/ixpay-pro/internal/infrastructure/redis"
	"github.com/ix-pay/ixpay-pro/internal/infrastructure/snowflake"
	"github.com/ix-pay/ixpay-pro/internal/infrastructure/task"
)

import (
	_ "github.com/ix-pay/ixpay-pro/docs"
)

// Injectors from wire.go:

// InitializeApp 初始化应用程序
// wire会根据ProviderSet自动生成依赖注入代码
func InitializeApp() (*Application, error) {
	configConfig, err := config.LoadConfig()
	if err != nil {
		return nil, err
	}
	loggerLogger := logger.NewLogger(configConfig)
	postgresDB, err := database.NewPostgresDB(configConfig, loggerLogger)
	if err != nil {
		return nil, err
	}
	jwtAuth, err := auth.NewJWTAuth(configConfig, loggerLogger)
	if err != nil {
		return nil, err
	}
	redisClient, err := redis.NewRedisClient(configConfig, loggerLogger)
	if err != nil {
		return nil, err
	}
	permissionManager := auth.NewPermissionManager(redisClient, loggerLogger)
	wxUserRepository := repository.NewWXUserRepository(postgresDB)
	wxAuthSessionRepository := repository.NewWXAuthSessionRepository(postgresDB)
	wxAuthService := service.NewWXAuthService(configConfig, jwtAuth, loggerLogger, wxUserRepository, wxAuthSessionRepository)
	authController := wxapi.NewAuthController(wxAuthService, loggerLogger)
	paymentRepository := repository.NewPaymentRepository(postgresDB)
	taskManager := task.NewTaskManager(loggerLogger)
	paymentService := service.NewPaymentService(paymentRepository, loggerLogger, wxAuthService, taskManager)
	paymentController := wxapi.NewPaymentController(paymentService, loggerLogger)
	appWX, err := wx.NewAppWX(loggerLogger, postgresDB, jwtAuth, permissionManager, authController, paymentController)
	if err != nil {
		return nil, err
	}
	userRepository := repository2.NewUserRepository(postgresDB)
	snowflakeSnowflake, err := snowflake.SetupSnowflake(configConfig)
	if err != nil {
		return nil, err
	}
	userService := service2.NewUserService(userRepository, jwtAuth, configConfig, loggerLogger, redisClient, snowflakeSnowflake)
	baseapiAuthController := baseapi.NewAuthController(userService, loggerLogger)
	userController := baseapi.NewUserController(userService, loggerLogger)
	taskController := baseapi.NewTaskController(taskManager, loggerLogger)
	appBase, err := base.NewAppBase(loggerLogger, postgresDB, jwtAuth, permissionManager, baseapiAuthController, userController, taskController, userRepository)
	if err != nil {
		return nil, err
	}
	application, err := NewApplication(configConfig, loggerLogger, postgresDB, jwtAuth, permissionManager, appWX, appBase)
	if err != nil {
		return nil, err
	}
	return application, nil
}

// wire.go:

// 定义依赖注入的提供者
var ProviderSet = wire.NewSet(config.LoadConfig, logger.NewLogger, database.NewPostgresDB, redis.NewRedisClient, auth.NewJWTAuth, snowflake.SetupSnowflake, auth.NewPermissionManager, task.NewTaskManager, NewApplication)
